### ISSUE TITLE
Can swap again during move.

### ISSUE THREAD

**Issue by ColeRominger** [autistic-ninja/Match3#4] opened 2020-02-03 23:52 UTC
If I swap but it's not a match I can quickly swap from the position that is invalid. In effect, nullifying the logic around matching and forcing another swap.

**Comment by thinkier-tim** [comment] 2020-02-04 00:08
there is a half-second between heartbeats (actions), in order to make it more obvious what is happening when. this will be optimized out later, when there is less timer dependency.

the above may or may not be relevant; i am unable to reproduce the issue.

**Comment by ColeRominger** [comment] 2020-02-04 00:38
Timing seems unrelated. Why would a moving action be available during the move?

**Comment by thinkier-tim** [comment] 2020-02-04 01:27
am now able to reproduce. this issue is due to a faulty state machine. uncertain where to begin fixing.

**Comment by ColeRominger** [comment] 2020-02-04 01:28
https://autisticninja.slack.com/files/USEA9QHUH/FTH493KM3/swap_during_move.mp4

**Comment by ColeRominger** [comment] 2020-02-04 01:34
Why can a move be done during a pause? When does the move relinquish control? Is the pause something done within the move unit or after?

**Comment by thinkier-tim** [comment] 2020-02-05 00:21
Having given a lot of thought to this, and I believe this is intended behavior, as a reflex-based "advanced" move (or some such). I enjoy the ability to move a piece more than one space, and I enjoy that it's more difficult to pull off than a standard move, but reaps greater rewards.

Not sure whether to mark this "won't fix", or "feature not bug". I will say that if I later break this functionality, someone should remind me that I think this is part of the game.

**Comment by thinkier-tim** [comment] 2020-02-05 01:13
As a matter of fact, I think I'd like to re-implement this properly at a later date.

Tabling this until later so I can figure out exactly why it works, and tweak it a bit. (See cards)

**Closed by thinkier-tim** 2020-02-05 01:13 UTC
